### ISSUE TITLE
Error: ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by stormlrd** [tmtk75/aws-cloudwatch-chart-slack#2]
Error: ENOENT: no such file or directory, open ''
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at /Users/stormlrd/dev/clones/aws-cloudwatch-chart-slack/dist/upload.js:16:18
    at upload (/Users/stormlrd/dev/clones/aws-cloudwatch-chart-slack/dist/upload.js:9:10)
    at /Users/stormlrd/dev/clones/aws-cloudwatch-chart-slack/dist/index.js:36:44

running from command line.
SLACK_CHANNEL_NAME=#mine ./bin/slack-cloudwatch-chart i-4x0weod9

have done an npm install in the cloned folder. 

had the following errors:

(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:46469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Any ideas appreciated.

**Comment by stormlrd** [comment]
I've done a number of things to move forward and am now getting this:

 env SLACK_CHANNEL_NAME=#mine ./bin/slack-cloudwatch-chart i-4e0c41d9
Error: phantomjs://code/gen-chart.js:48:185
map@[native code]
phantomjs://code/gen-chart.js:46:31
global code@phantomjs://code/gen-chart.js:121:5

```
at ChildProcess.<anonymous> (/Users/stormlrd/dev/clones/aws-cloudwatch-chart-slack/dist/proc-gen-chart.js:39:50)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:877:16)
at Socket.<anonymous> (internal/child_process.js:334:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:493:12)
```

I've had to modify the package.json to upgrade the packages and I removed the dev section of it as Gulp is using depreciated things that gave errors..

  "_phantomChildren": {
    "buffer": "5.0.0",
    "crypto-browserify": "3.11.0",
    "jmespath": "0.15.0",
    "lodash": "4.16.3",
    "querystring": "0.2.0",
    "url": "0.11.0"
  },
  "dependencies": {
    "aws-sdk": "^2.6.6",
    "c3": "^0.4.11",
    "form-data": "^2.1.1",
    "immutable": "^3.8.1",
    "minimist": "^1.2.0",
    "moment": "^2.15.1",
    "node-fetch": "^1.6.3",
    "phantomjs-prebuilt": "^2.1.1"
  },
  "_nodeVersion": "6.7.0",
  "_npmVersion": "3.10.8",

my npm install output is now this:

npm install

> phantomjs-prebuilt@2.1.13 install /Users/weo/dev/clones/aws-cloudwatch-chart-slack/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/jk/s3n_bbdj0mnfvqk8vkc5wfqr0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/weo/dev/clones/aws-cloudwatch-chart-slack/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/jk/s3n_bbdj0mnfvqk8vkc5wfqr0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1475704331351/phantomjs-2.1.1-macosx -> /Users/weo/dev/clones/aws-cloudwatch-chart-slack/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/weo/dev/clones/aws-cloudwatch-chart-slack/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
├─┬ aws-sdk@2.6.6 
│ ├─┬ buffer@4.9.1 
│ │ ├── base64-js@1.2.0 
│ │ ├── ieee754@1.1.8 
│ │ └── isarray@1.0.0 
│ ├── crypto-browserify@1.0.9 
│ ├── jmespath@0.15.0 
│ ├── querystring@0.2.0 
│ ├── sax@1.1.5 
│ ├─┬ url@0.10.3 
│ │ └── punycode@1.3.2 
│ ├── xml2js@0.4.15 
│ └─┬ xmlbuilder@2.6.2 
│   └── lodash@3.5.0 
├─┬ c3@0.4.11 
│ └── d3@3.5.17 
├─┬ form-data@2.1.1 
│ ├── asynckit@0.4.0 
│ ├─┬ combined-stream@1.0.5 
│ │ └── delayed-stream@1.0.0 
│ └─┬ mime-types@2.1.12 
│   └── mime-db@1.24.0 
├── immutable@3.8.1 
├── minimist@1.2.0 
├── moment@2.15.1 
├─┬ node-fetch@1.6.3 
│ ├─┬ encoding@0.1.12 
│ │ └── iconv-lite@0.4.13 
│ └── is-stream@1.1.0 
└─┬ phantomjs-prebuilt@2.1.13 
  ├── es6-promise@4.0.5 
  ├─┬ extract-zip@1.5.0 
  │ ├─┬ concat-stream@1.5.0 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── typedarray@0.0.6 
  │ ├── debug@0.7.4 
  │ ├─┬ mkdirp@0.5.0 
  │ │ └── minimist@0.0.8 
  │ └─┬ yauzl@2.4.1 
  │   └─┬ fd-slicer@1.0.1 
  │     └── pend@1.2.0 
  ├─┬ fs-extra@0.30.0 
  │ ├── graceful-fs@4.1.9 
  │ ├── jsonfile@2.4.0 
  │ ├── klaw@1.3.0 
  │ ├── path-is-absolute@1.0.1 
  │ └─┬ rimraf@2.5.4 
  │   └─┬ glob@7.1.0 
  │     ├── fs.realpath@1.0.0 
  │     ├─┬ inflight@1.0.5 
  │     │ └── wrappy@1.0.2 
  │     ├─┬ minimatch@3.0.3 
  │     │ └─┬ brace-expansion@1.1.6 
  │     │   ├── balanced-match@0.4.2 
  │     │   └── concat-map@0.0.1 
  │     └── once@1.4.0 
  ├─┬ hasha@2.2.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├── kew@0.7.0 
  ├── progress@1.1.8 
  ├─┬ request@2.74.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.4.1 
  │ ├── bl@1.1.2 
  │ ├── caseless@0.11.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@1.0.1 
  │ │ └─┬ async@2.0.1 
  │ │   └── lodash@4.16.3 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ └─┬ is-my-json-valid@2.15.0 
  │ │   ├── generate-function@2.0.0 
  │ │   ├─┬ generate-object-property@1.2.0 
  │ │   │ └── is-property@1.0.2 
  │ │   ├── jsonpointer@4.0.0 
  │ │   └── xtend@4.0.1 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.14.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.2.1 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.3.1 
  │ └── tunnel-agent@0.4.3 
  ├─┬ request-progress@2.0.1 
  │ └── throttleit@1.0.0 
  └─┬ which@1.2.11 
    └── isexe@1.1.2 

was able to retrieve the json using the command:
node ./dist/print-stats.js [options] <instance-id> > test.json

then running:
cat ./test.json | node_modules/.bin/phantomjs  ./dist/gen-chart.js

results in:
phantomjs://code/gen-chart.js:48:185
map@[native code]
phantomjs://code/gen-chart.js:46:31
global code@phantomjs://code/gen-chart.js:121:5

Line 48 in gen-chart.js is:
      if (stats.Datapoints.length < 2) {
        throw new Error("Number of datapoints is less than 2 for " + MetricName + " of " + stats.InstanceId + ". There is a possibility InstanceId was wrong. " + JSON.stringify(stats));
      }

[{"Namespace":"AWS/EC2","InstanceId":"i-1e0c41d9","EndTime":"2016-10-05T22:31:39.389Z","StartTime":"2016-10-04T22:31:39.389Z","Period":1800,"ResponseMetadata":{"RequestId":"7bd4f2ad-8b4b-11e6-872f-038e2e7795f4"},"Label":"CPUUtilization","Datapoints":[{"Timestamp":"2016-10-05T22:01:00.000Z","Average":0.05555555555555555,"Unit":"Percent"}]}]

**Comment by tmtk75** [comment]
Hi @stormlrd, sorry for very late reply.

With what environment did you try?

I only tested with next versions and on macOS.

```
$ npm -v
2.14.12
$ node -v
v4.3.1
```

**Comment by tmtk75** [comment]
I'll close because of getting stale.
